language: node_js
node_js:
- '0.11'
before_install:
- cp travis-ci.sh $HOME/
- chmod +x $HOME/travis-ci.sh
before_script:
- $HOME/travis-ci.sh before-script
script:
- $HOME/travis-ci.sh script
after_script:
- $HOME/travis-ci.sh after-script
after_success:
- $HOME/travis-ci.sh after-success
before_deploy:
- $HOME/travis-ci.sh before-deploy
- cd built
deploy:
  matrix:
  - provider: releases
    api_key:
      secure: ej3cDUpdrxLbG5gAyOVbVCBGS8c0gPLp46XaU6/iS+aQuNHseyTLUM8Ttd4n3dFeFHmsIXcP+jCVXRlsJwUa+SDGepCmvMtaHzWjfex/GImRz706sj+s1hggs05wvmZjWurwngWk5GhBBdsgJRg8+kfuZ4iOKM3UFSnCfodURbw=
    file:
    - kalabox-win-$TRAVIS_TAG.zip
    - kalabox-osx-$TRAVIS_TAG.zip
    - kalabox-linux32-$TRAVIS_TAG.zip
    - kalabox-linux64-$TRAVIS_TAG.zip
    skip_cleanup: true
    on:
      repo: kalabox/kalabox
      all_branches: true
      tags: true
  - provider: cloudfiles
    username: kalamuna
    api_key:
      secure: kZ1n6iNPWbs9ENeH4bJoEwKoJ0jn/V1tY+BwNXMeVsf86theVeePZTqRKaAz76IpHVRwZnFVPbzjzdYKEm8Qnz45rUnfwyBDsn+/RC/76i09AnZ/oeX+21h9IoabA5N7cMg4Gu10eFmjQDvJKm8z1v+jZB6A1tP1sXyi+Q2xazQ=
    region: ord
    container: kb2
    skip_cleanup: true
    on:
      repo: kalabox/kalabox
      branch: master
cache:
  directories:
  - node_modules
notifications:
  slack:
    rooms:
    - kalamuna:dP7cYTtQ5mOBCp9cpyHHnUYN#kalabox
  irc:
  - chat.freenode.net#kalabox
  email:
    recipients:
    - mike@kalamuna.com
    - alec@kalamuna.com
    - coder1@gmail.com
    on_success: always
